# Generated by Django 4.0.2 on 2022-03-06 07:08

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_list_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 7, 8, 37, 532116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='list',
            name='watched_list',
            field=models.ManyToManyField(blank=True, default='', related_name='watched_list_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
