# Generated by Django 4.0.2 on 2022-03-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_list_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
