# Generated by Django 4.0.2 on 2022-05-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_list_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='watched_list',
        ),
        migrations.AddField(
            model_name='user',
            name='watched_list',
            field=models.ManyToManyField(blank=True, default='', related_name='watched_list_by_user', to='auctions.List'),
        ),
    ]
