# Generated by Django 4.0.2 on 2022-05-06 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_list_watched_list_user_watched_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watched_list',
        ),
        migrations.AddField(
            model_name='list',
            name='watched_list',
            field=models.ManyToManyField(blank=True, default='', related_name='watched_list_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
