# Generated by Django 4.0.2 on 2022-05-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_user_watched_list_list_watched_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='watched_list',
        ),
        migrations.AddField(
            model_name='user',
            name='watched_list',
            field=models.ManyToManyField(blank=True, default='', related_name='watched_list_by_user', to='auctions.List'),
        ),
    ]
